import type { QuizQuestionConfig } from "@/types/quiz";

import {
  AppetizersIcon,
  BudgetIcon,
  CheeseIcon,
  DateNightIcon,
  DessertIcon,
  DinnerAtHomeIcon,
  EveningWithFriendsIcon,
  FishIcon,
  FreshLightIcon,
  FruityIcon,
  GiftIcon,
  HigherTierIcon,
  MeatIcon,
  MidRangeIcon,
  NeutralWineLevelIcon,
  PastaIcon,
  SlightlySweetIcon,
  SlightlyTartIcon,
  SomethingTastyIcon,
  SpicyFlavorIcon,
  UniversalIcon,
} from "@/components/quiz/QuizQuestion/config/quizIcons";

export const beginnerQuestions: QuizQuestionConfig[] = [
  {
    step: 2,
    question: "What type of wine do you prefer?",
    apiField: "WINE_TYPE",
    options: [
      {
        id: "premium",
        title: "Premium",
        description: "",
        apiValue: "PREMIUM",
        Icon: BudgetIcon,
      },
      {
        id: "red",
        title: "Red",
        description: "",
        apiValue: "RED",
        Icon: MidRangeIcon,
      },
      {
        id: "rose",
        title: "Rosé",
        description: "",
        apiValue: "ROSE",
        Icon: HigherTierIcon,
      },
      {
        id: "sparkling",
        title: "Sparkling",
        description: "",
        apiValue: "SPARKLING",
        Icon: NeutralWineLevelIcon,
      },
      {
        id: "not-preference",
        title: "No preference",
        description: "",
        apiValue: "NO_PREFERENCE",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
  {
    step: 3,
    question: "What occasion are you choosing wine for?",
    apiField: "EVENT",
    options: [
      {
        id: "date-night",
        title: "Date Night",
        description: "",
        apiValue: "DATE",
        Icon: DateNightIcon,
      },
      {
        id: "evening-with-friends",
        title: "Evening With Friends",
        description: "",
        apiValue: "DINNER_WITH_FRIENDS",
        Icon: EveningWithFriendsIcon,
      },
      {
        id: "picnic",
        title: "Picnic",
        description: "",
        apiValue: "PICNIC",
        Icon: DinnerAtHomeIcon,
      },
      {
        id: "gift",
        title: "A Gift",
        description: "",
        apiValue: "GIFT",
        Icon: GiftIcon,
      },
      {
        id: "universal",
        title: "Universal",
        description: "",
        apiValue: "UNIVERSAL",
        Icon: SomethingTastyIcon,
      },
    ],
  },
  {
    step: 4,
    question: "What are you planning to eat?",
    apiField: "FOOD_CATEGORY",
    options: [
      {
        id: "meat",
        title: "Meat",
        description: "",
        apiValue: "MEAT",
        Icon: MeatIcon,
      },
      {
        id: "fish",
        title: "Fish",
        description: "",
        apiValue: "FISH_SEAFOOD",
        Icon: FishIcon,
      },
      {
        id: "pasta",
        title: "Pasta",
        description: "",
        apiValue: "PASTA_PIZZA",
        Icon: PastaIcon,
      },
      {
        id: "cheese",
        title: "Cheese",
        description: "",
        apiValue: "CHEESE",
        Icon: CheeseIcon,
      },
      {
        id: "light-dishes",
        title: "Light Dishes",
        description: "",
        apiValue: "LIGHT_DISHES",
        Icon: AppetizersIcon,
      },
      {
        id: "dessert",
        title: "Dessert",
        description: "",
        apiValue: "DESSERT",
        Icon: DessertIcon,
      },
      {
        id: "universal",
        title: "Universal",
        description: "",
        apiValue: "UNIVERSAL",
        Icon: UniversalIcon,
      },
    ],
  },
  {
    step: 5,
    question: "What wine level feels comfortable for you?",
    apiField: "PRICE_LEVEL",
    options: [
      {
        id: "budget",
        title: "Budget",
        description: "Affordable but tasty",
        apiValue: "BUDGET",
        Icon: BudgetIcon,
      },
      {
        id: "mid-range",
        title: "Mid-Range",
        description: "Something quality without going overboard",
        apiValue: "MID_RANGE",
        Icon: MidRangeIcon,
      },
      {
        id: "higher-tier",
        title: "Higher Tier",
        description: "I want something more interesting",
        apiValue: "HIGHER_TIER",
        Icon: HigherTierIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "Doesn’t matter, as long as it tastes good",
        apiValue: "NO-PREFERENCE",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
  {
    step: 6,
    question: "Which aroma notes do you prefer?",
    apiField: "AROMA_NOTES",
    options: [
      {
        id: "fruity",
        title: "Fruity",
        description: "",
        apiValue: "FRUITY",
        Icon: FruityIcon,
      },
      {
        id: "mineral",
        title: "Mineral",
        description: "",
        apiValue: "MINERAL",
        Icon: FreshLightIcon,
      },
      {
        id: "oaky-vanilla",
        title: "Oaky / Vanilla",
        description: "",
        apiValue: "OAKY",
        Icon: SlightlySweetIcon,
      },
      {
        id: "spicy",
        title: "Spicy",
        description: "",
        apiValue: "SPICY",
        Icon: SpicyFlavorIcon,
      },
      {
        id: "floral",
        title: "Floral",
        description: "",
        apiValue: "FLORAL",
        Icon: SlightlyTartIcon,
      },
      {
        id: "nutty-honey",
        title: "Nutty / Honey",
        description: "",
        apiValue: "NUTTY_HONEY",
        Icon: HigherTierIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "",
        apiValue: "NO-PREFERENCE",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
];