import type { QuizQuestionConfig } from "@/types/quiz";

import {
  BudgetIcon,
  EveningWithFriendsIcon,
  FreshLightIcon,
  FruityFlavorIcon,
  HigherTierIcon,
  MidRangeIcon,
  NeutralIcon,
  NeutralWineLevelIcon,
  SlightlyTartIcon,
  SomethingTastyIcon,
  UniversalIcon,
} from "@/components/quiz/QuizQuestion/config/quizIcons";

export const connoisseurQuestions: QuizQuestionConfig[] = [
  {
    step: 2,
    question: "Which regions are you interested in?",
    apiField: "REGION",
    options: [
      {
        id: "burgundy",
        title: "Burgundy",
        description: "",
        apiValue: "BURGUNDY",
        Icon: HigherTierIcon,
      },
      {
        id: "bordeaux",
        title: "Bordeaux",
        description: "",
        apiValue: "BORDEAUX",
        Icon: MidRangeIcon,
      },
      {
        id: "piedmont",
        title: "Piedmont",
        description: "",
        apiValue: "PIEDMONT",
        Icon: NeutralIcon,
      },
      {
        id: "rioja",
        title: "Rioja",
        description: "",
        apiValue: "RIOJA",
        Icon: HigherTierIcon,
      },
      {
        id: "niche-regions",
        title: "Niche Regions",
        description: "",
        apiValue: "NICHE_REGIONS",
        Icon: SomethingTastyIcon,
      },
      {
        id: "provence",
        title: "Provence",
        description: "",
        apiValue: "PROVENCE",
        Icon: HigherTierIcon,
      },
      {
        id: "ribera-del-duero",
        title: "Ribera del Duero",
        description: "",
        apiValue: "RIBERA_DEL_DUERO",
        Icon: MidRangeIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "",
        apiValue: "NO_PREFERENCE",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
  {
    step: 3,
    question: "Do you have any wine values preferences?",
    apiField: "ENVIRONMENTAL_ATTRIBUTES",
    options: [
      {
        id: "vegan",
        title: "Vegan",
        description: "",
        apiValue: "VEGAN",
        Icon: HigherTierIcon,
      },
      {
        id: "organic",
        title: "Organic",
        description: "",
        apiValue: "ORGANIC",
        Icon: MidRangeIcon,
      },
      {
        id: "biodynamic",
        title: "Biodynamic",
        description: "",
        apiValue: "BIODYNAMIC",
        Icon: HigherTierIcon,
      },
      {
        id: "sustainable",
        title: "Sustainable",
        description: "",
        apiValue: "SUSTAINABLE",
        Icon: FreshLightIcon,
      },
      {
        id: "natural",
        title: "Natural",
        description: "",
        apiValue: "NATURAL",
        Icon: HigherTierIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "",
        apiValue: "NO_PREFERENCE",
        Icon: NeutralIcon,
      },
    ],
  },
  {
    step: 4,
    question: "Which wine style do you prefer?",
    apiField: "WINE_STYLE",
    options: [
      {
        id: "light-bodied",
        title: "Light Bodied",
        description: "",
        apiValue: "LIGHT_BODIED",
        Icon: FreshLightIcon,
      },
      {
        id: "medium-bodied",
        title: "Medium Bodied",
        description: "",
        apiValue: "MEDIUM_BODIED",
        Icon: SlightlyTartIcon,
      },
      {
        id: "full-bodied",
        title: "Full Bodied",
        description: "",
        apiValue: "FULL_BODIED",
        Icon: HigherTierIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "",
        apiValue: "NO_PREFERENCE",
        Icon: UniversalIcon,
      },
    ],
  },
  {
    step: 5,
    question: "Which grape varieties do you like?",
    apiField: "GRAPE_VARIETY",
    options: [
      {
        id: "cabernet-sauvignon",
        title: "Cabernet Sauvignon",
        description: "",
        apiValue: "CABERNET_SAUVIGNON",
        Icon: BudgetIcon,
      },
      {
        id: "merlot",
        title: "Merlot",
        description: "",
        apiValue: "MERLOT",
        Icon: MidRangeIcon,
      },
      {
        id: "pinot-noir",
        title: "Pinot Noir",
        description: "",
        apiValue: "PINOT_NOIR",
        Icon: HigherTierIcon,
      },
      {
        id: "chardonnay",
        title: "Chardonnay",
        description: "",
        apiValue: "CHARDONNAY",
        Icon: FruityFlavorIcon,
      },
      {
        id: "muscat",
        title: "Muscat",
        description: "",
        apiValue: "MUSCAT",
        Icon: FruityFlavorIcon,
      },
      {
        id: "grenache",
        title: "Grenache",
        description: "",
        apiValue: "GRENACHE",
        Icon: NeutralWineLevelIcon,
      },
      {
        id: "blend",
        title: "Blend",
        description: "",
        apiValue: "BLEND",
        Icon: MidRangeIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "",
        apiValue: "NO_PREFERENCE",
        Icon: UniversalIcon,
      },
    ],
  },
  {
    step: 6,
    question: "What aging potential are you looking for?",
    apiField: "AGING_POTENTIAL",
    options: [
      {
        id: "drink-now",
        title: "Drink Now",
        description: "I want a wine that is ready to enjoy now",
        apiValue: "DRINK_NOW",
        Icon: BudgetIcon,
      },
      {
        id: "short-term-aging",
        title: "Short-Term Aging",
        description: "I want a wine that can improve over the next few years",
        apiValue: "SHORT_TERM_AGING",
        Icon: HigherTierIcon,
      },
      {
        id: "long-term-aging",
        title: "Long-Term Aging",
        description: "I want a wine that can develop over time",
        apiValue: "LONG_TERM_AGING",
        Icon: EveningWithFriendsIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "I’m open to recommendations",
        apiValue: "NO_PREFERENCE",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
];