import type { QuizQuestionConfig } from "@/types/quiz";

import {
  AppetizersIcon,
  BudgetIcon,
  CheeseIcon,
  DessertIcon,
  FishIcon,
  FruityFlavorIcon,
  HigherTierIcon,
  MeatIcon,
  MidRangeIcon,
  NeutralWineLevelIcon,
  PastaIcon,
  SpicyFlavorIcon,
  UniversalIcon,
} from "@/components/quiz/QuizQuestion/config/quizIcons";

export const enthusiastQuestions: QuizQuestionConfig[] = [
  {
    step: 2,
    question: "Which sweetness level do you prefer?",
    apiField: "SWEETNESS",
    options: [
      {
        id: "dry",
        title: "Dry",
        description: "",
        apiValue: "DRY",
        Icon: BudgetIcon,
      },
      {
        id: "semi-dry",
        title: "Semi-Dry",
        description: "",
        apiValue: "SEMI_DRY",
        Icon: MidRangeIcon,
      },
      {
        id: "semi-sweet",
        title: "Semi-Sweet",
        description: "",
        apiValue: "SEMI_SWEET",
        Icon: HigherTierIcon,
      },
      {
        id: "sweet",
        title: "Sweet",
        description: "",
        apiValue: "SWEET",
        Icon: NeutralWineLevelIcon,
      },
      {
        id: "brut",
        title: "Brut",
        description: "",
        apiValue: "BRUT",
        Icon: FruityFlavorIcon,
      },
      {
        id: "open-to-experiment",
        title: "Open To Experiment",
        description: "",
        apiValue: "OPEN_TO_EXPERIMENT",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
  {
    step: 3,
    question: "Which wine countries do you prefer?",
    apiField: "COUNTRY",
    options: [
      {
        id: "italy",
        title: "Italy",
        description: "",
        apiValue: "ITALY",
        Icon: BudgetIcon,
      },
      {
        id: "france",
        title: "France",
        description: "",
        apiValue: "FRANCE",
        Icon: MidRangeIcon,
      },
      {
        id: "spain",
        title: "Spain",
        description: "",
        apiValue: "SPAIN",
        Icon: HigherTierIcon,
      },
      {
        id: "usa",
        title: "USA",
        description: "",
        apiValue: "USA",
        Icon: FruityFlavorIcon,
      },
      {
        id: "portugal",
        title: "Portugal",
        description: "",
        apiValue: "PORTUGAL",
        Icon: NeutralWineLevelIcon,
      },
      {
        id: "australia",
        title: "Australia",
        description: "",
        apiValue: "AUSTRALIA",
        Icon: BudgetIcon,
      },
      {
        id: "open-to-experiment",
        title: "Open To Experiment",
        description: "",
        apiValue: "OPEN_TO_EXPERIMENT",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
  {
    step: 4,
    question: "Which grape varieties do you like?",
    apiField: "GRAPE_VARIETY",
    options: [
      {
        id: "cabernet-sauvignon",
        title: "Cabernet Sauvignon",
        description: "",
        apiValue: "CABERNET_SAUVIGNON",
        Icon: BudgetIcon,
      },
      {
        id: "merlot",
        title: "Merlot",
        description: "",
        apiValue: "MERLOT",
        Icon: MidRangeIcon,
      },
      {
        id: "pinot-noir",
        title: "Pinot Noir",
        description: "",
        apiValue: "PINOT_NOIR",
        Icon: HigherTierIcon,
      },
      {
        id: "chardonnay",
        title: "Chardonnay",
        description: "",
        apiValue: "CHARDONNAY",
        Icon: FruityFlavorIcon,
      },
      {
        id: "muscat",
        title: "Muscat",
        description: "",
        apiValue: "MUSCAT",
        Icon: FruityFlavorIcon,
      },
      {
        id: "grenache",
        title: "Grenache",
        description: "",
        apiValue: "GRENACHE",
        Icon: NeutralWineLevelIcon,
      },
      {
        id: "blend",
        title: "Blend",
        description: "",
        apiValue: "BLEND",
        Icon: MidRangeIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "",
        apiValue: "NO_PREFERENCE",
        Icon: MidRangeIcon,
      },
    ],
  },
  {
    step: 5,
    question: "Which aroma notes do you prefer?",
    apiField: "AROMA_NOTES",
    options: [
      {
        id: "fruity",
        title: "Fruity",
        description: "",
        apiValue: "FRUITY",
        Icon: FruityFlavorIcon,
      },
      {
        id: "mineral",
        title: "Mineral",
        description: "",
        apiValue: "MINERAL",
        Icon: MidRangeIcon,
      },
      {
        id: "oaky-vanilla",
        title: "Oaky / Vanilla",
        description: "",
        apiValue: "OAKY",
        Icon: HigherTierIcon,
      },
      {
        id: "spicy",
        title: "Spicy",
        description: "",
        apiValue: "SPICY",
        Icon: SpicyFlavorIcon,
      },
      {
        id: "floral",
        title: "Floral",
        description: "",
        apiValue: "FLORAL",
        Icon: HigherTierIcon,
      },
      {
        id: "nutty-honey",
        title: "Nutty / Honey",
        description: "",
        apiValue: "NUTTY_HONEY",
        Icon: HigherTierIcon,
      },
      {
        id: "no-preference",
        title: "No Preference",
        description: "",
        apiValue: "NO_PREFERENCE",
        Icon: NeutralWineLevelIcon,
      },
    ],
  },
  {
    step: 6,
    question: "What are you planning to eat?",
    apiField: "FOOD_CATEGORY",
    options: [
      {
        id: "light-dishes",
        title: "Light Dishes",
        description: "",
        apiValue: "LIGHT_DISHES",
        Icon: MidRangeIcon,
      },
      {
        id: "fish-seafood",
        title: "Fish / Seafood",
        description: "",
        apiValue: "FISH_SEAFOOD",
        Icon: FishIcon,
      },
      {
        id: "pasta-pizza",
        title: "Pasta / Pizza",
        description: "",
        apiValue: "PASTA_PIZZA",
        Icon: PastaIcon,
      },
      {
        id: "appetizers",
        title: "Appetizers",
        description: "",
        apiValue: "LIGHT_DISHES",
        Icon: AppetizersIcon,
      },
      {
        id: "cheese",
        title: "Cheese",
        description: "",
        apiValue: "CHEESE",
        Icon: CheeseIcon,
      },
      {
        id: "dessert",
        title: "Dessert",
        description: "",
        apiValue: "DESSERT",
        Icon: DessertIcon,
      },
      {
        id: "meat",
        title: "Meat",
        description: "",
        apiValue: "MEAT",
        Icon: MeatIcon,
      },
      {
        id: "universal",
        title: "Universal",
        description: "",
        apiValue: "UNIVERSAL",
        Icon: UniversalIcon,
      },
    ],
  },
];