export type Wine = {
  id: number;
  name: string;
  type: string;
  volumeMl: number;
  description: string;
  imageUrl: string;
  rating: number;
  alcoholPercentage: number;
  sweetnessLevel: string;
  grapeVariety: string;
  agingMonths: number;
  environmentalAttributes: string[];
  fermentationType: string;
  vintage: number;
  appellation: string;
  producerName: string;
  countryName: string;
  region: string;
};
