export const FOOD_PAIRING_BACKGROUND_CLASSES = [
  "wine-food-pairings__card--tone-wood",
  "wine-food-pairings__card--tone-honey",
  "wine-food-pairings__card--tone-clay",
  "wine-food-pairings__card--tone-olive",
  "wine-food-pairings__card--tone-berry",
  "wine-food-pairings__card--tone-cream",
  "wine-food-pairings__card--tone-orange-dark",
  "wine-food-pairings__card--tone-sand",
  "wine-food-pairings__card--tone-orange",
  "wine-food-pairings__card--tone-salmon",
  "wine-food-pairings__card--tone-lemon",
  "wine-food-pairings__card--tone-moss",
  "wine-food-pairings__card--tone-peach",
  "wine-food-pairings__card--tone-caramel",
  "wine-food-pairings__card--tone-red",
  "wine-food-pairings__card--tone-brass",
  "wine-food-pairings__card--tone-beige",
  "wine-food-pairings__card--tone-coral",
  "wine-food-pairings__card--tone-yellow",
  "wine-food-pairings__card--tone-sky",
  "wine-food-pairings__card--tone-pumpkin",
] as const;